<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 cubesat_1u.glb --transform
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/cubesat_1u-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Mesh geometry={gltf.nodes['1RU-GenericCubesat_1'].geometry} material={gltf.materials['ICECube-grey-light']} />
    <T.Mesh geometry={gltf.nodes['1RU-GenericCubesat_2'].geometry} material={gltf.materials['Atlas_black-sm']} />
    <T.Mesh geometry={gltf.nodes['1RU-GenericCubesat_3'].geometry} material={gltf.materials['ICECube-grey-dark']} />
    <T.Mesh geometry={gltf.nodes['1RU-GenericCubesat_4'].geometry} material={gltf.materials['ICECube-silverfoil']} />
    <T.Mesh geometry={gltf.nodes['1RU-GenericCubesat_5'].geometry} material={gltf.materials['ICECube-black-sm']} />
    <T.Mesh geometry={gltf.nodes['1RU-GenericCubesat_6'].geometry} material={gltf.materials['ICECube-gold']} />
    <T.Mesh geometry={gltf.nodes['1RU-GenericCubesat_7'].geometry} material={gltf.materials['ICECube-black-sm']} />
    <T.Mesh geometry={gltf.nodes['1RU-GenericCubesat_8'].geometry} material={gltf.materials['ICECube-solaredges']} />
    <T.Mesh geometry={gltf.nodes['1RU-GenericCubesat_9'].geometry} material={gltf.materials['ICECube-solar1']} />
    <T.Mesh geometry={gltf.nodes['1RU-GenericCubesat_10'].geometry} material={gltf.materials['Afta-solar77']} />
    <T.Mesh geometry={gltf.nodes['1RU-GenericCubesat_11'].geometry} material={gltf.materials['Afta-solar1']} />
    <T.Mesh geometry={gltf.nodes['1RU-GenericCubesat_12'].geometry} material={gltf.materials['Afta-solar22']} />
    <T.Mesh geometry={gltf.nodes['1RU-GenericCubesat_13'].geometry} material={gltf.materials['Afta-solar77']} />
    <T.Mesh geometry={gltf.nodes['1RU-GenericCubesat_14'].geometry} material={gltf.materials['Afta-solar77']} />
    <T.Mesh geometry={gltf.nodes['1RU-GenericCubesat_15'].geometry} material={gltf.materials['Afta-solar55']} />
    <T.Mesh geometry={gltf.nodes['1RU-GenericCubesat_16'].geometry} material={gltf.materials['Afta-solar66']} />
    <T.Mesh geometry={gltf.nodes['1RU-GenericCubesat_17'].geometry} material={gltf.materials['Default.002']} />
    <T.Mesh geometry={gltf.nodes['1RU-GenericCubesat_18'].geometry} material={gltf.materials['ICECube-yellow-tape']} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
