session_name: servers
windows:
  - window_name: hosted-servers
    layout: even-horizontal
    panes:
      - shell_command: # backend server
          - just host-backend
      - shell_command: # frontend server
          - just host-frontend
