session_name: servers
shell_command_before:
  - >
      if [ -n "$IN_NIX_SHELL" ]; then nix develop; fi
windows:
  - window_name: hosted-servers
    layout: even-horizontal
    panes:
      - shell_command: # backend server
          - just host-backend
      - shell_command: # frontend server
          - just host-frontend
