session_name: servers
windows:
  - window_name: development-servers
    layout: even-horizontal
    panes:
      - shell_command: # backend server
          - just start-backend
      - shell_command: # frontend server
          - just start-frontend
