session_name: servers
shell_command_before:
  - >
      bash -c 'if [ -n "$IN_NIX_SHELL" ]; then nix develop; fi'
windows:
  - window_name: development-servers
    layout: even-horizontal
    panes:
      - shell_command: # backend server
          - just start-backend
      - shell_command: # frontend server
          - just start-frontend
